//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.DriverOrCar = new HashSet<DriverOrCar>();
        }
    
        public int Id { get; set; }
        public string VIN { get; set; }
        public int ModelId { get; set; }
        public int Year { get; set; }
        public int Weight { get; set; }
        public int Color { get; set; }
        public int EngineType { get; set; }
        public string TypeOfDrive { get; set; }
    
        public virtual CarsModel CarsModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverOrCar> DriverOrCar { get; set; }
    }
}
