//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverOrCar
    {
        public int DriverId { get; set; }
        public int CarId { get; set; }
        public string Nothing { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Drivers Drivers { get; set; }
    }
}
