//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GIBDDEntities : DbContext
    {
        public GIBDDEntities()
            : base("name=GIBDDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<CarsManufacturer> CarsManufacturer { get; set; }
        public virtual DbSet<CarsModel> CarsModel { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<ChangedStatus> ChangedStatus { get; set; }
        public virtual DbSet<DriverOrCar> DriverOrCar { get; set; }
        public virtual DbSet<DriverOrLicense> DriverOrLicense { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<License> License { get; set; }
        public virtual DbSet<LicenseOrCategories> LicenseOrCategories { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    }
}
